### ISSUE TITLE
Broken link to collision documentation

### ISSUE THREAD

**Issue by carlosferrazza** [eanswer/DiffHand#2]
Hi, I would like to understand more about the way collisions are handled, and found a comment (in the file BodyCuboid.cpp) that refers to the following document: https://www.overleaf.com/project/5cd0a78e0e41fe0f8632a42a

However, access to the link seems to be restricted. Could you please provide a working link?

Thanks!

**Comment by eanswer** [comment]
Sorry this line is supposed to be removed since it links to a private doc. The collision is handled by the penalty-based contact model presented in the [DiffHand](http://people.csail.mit.edu/jiex/papers/DiffHand/paper.pdf) paper, and more simulation details are enclosed in this attached [simulation doc](http://people.csail.mit.edu/jiex/papers/DiffHand/redmax_doc.pdf) (which is compiled from that overleaf doc).

**Comment by carlosferrazza** [comment]
Thanks for the link to the simulation doc!
