### ISSUE TITLE
C++ design (hanging pointers)

### ISSUE THREAD

**Issue by mikel-zhobro** [eanswer/DiffHand#3]
It is not clear what c++ design is followed for the project. 

How do you deal with free hanging pointers? Is the library meant to be used only through the python interface? Does pybind11 take care of the free hanging pointers?

**Comment by eanswer** [comment]
The library mainly provides interfaces to Python since most of the learning tools (e.g. solver, neural networks) are more accessible in Python. However, you can also make the project under `core` folder which will generate C++ executable file and you can run it. To integrate this project into your C++ codebase, you can add this project as a library in your own cmake configuration file.
